image: Ubuntu1604

environment:
  matrix:
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    PowerShellEdition: Desktop
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    PowerShellEdition: Core

# build:
#   parallel: true

build_script:
- ps: |
    whoami
    systeminfo
    Get-PSDrive
    $PSVersionTable | Out-String
    Get-Location
- ps: |
    Get-ChildItem env:*
