environment:
  matrix:
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2013
    PowerShellEdition: Desktop
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    PowerShellEdition: Desktop
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    PowerShellEdition: Desktop
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
    PowerShellEdition: Desktop
  - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu1604
  - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu1804

# Disable MSBuild mode
build: off

for:
-
  matrix:
    only:
      - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2013
      - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
  build_script:
  - ps: |
      whoami
      systeminfo
      Get-PSDrive
      $PSVersionTable | Out-String
      Get-Location
  - ps: |
      Get-ChildItem env:*
  - ps: |
      Get-Command -CommandType Application
  - ps: |
      Get-Module PowershellGet -ListAvailable
-
  matrix:
    only:
      - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu1604
      - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu1804
  build_script:
  - |
    whoami
    cat /etc/*release
    lscpu
    free
    df -h
    pwd
  - |
    printenv
